// HAND-WRITTEN (not generated by `pnpm abis`): the minimal token surface the
// facilitator bridge needs — the (v, r, s) transferWithAuthorization overload
// (present on our EIP3009 mocks and Circle FiatTokenV2+; only this overload is
// listed so viem never has to resolve between the two), plus the read/refund
// helpers. No errors: error decoding stays with gantryErrorsAbi.
//
// The two authorization EVENTS are here because `authorizationState` cannot
// answer the question the bridge's compensation path actually asks. That
// mapping is set to true by `transferWithAuthorization` AND by
// `cancelAuthorization`, so the boolean means "this nonce is spent", never
// "the money moved" — and only the events tell the two apart. Both are standard
// EIP-3009 and Circle's FiatTokenV2 emits them with these exact signatures.
export const eip3009TokenAbi = [
  {
    type: "event",
    name: "AuthorizationUsed",
    inputs: [
      { name: "authorizer", type: "address", indexed: true },
      { name: "nonce", type: "bytes32", indexed: true },
    ],
  },
  {
    type: "event",
    name: "AuthorizationCanceled",
    inputs: [
      { name: "authorizer", type: "address", indexed: true },
      { name: "nonce", type: "bytes32", indexed: true },
    ],
  },
  {
    type: "function",
    name: "transferWithAuthorization",
    stateMutability: "nonpayable",
    inputs: [
      { name: "from", type: "address" },
      { name: "to", type: "address" },
      { name: "value", type: "uint256" },
      { name: "validAfter", type: "uint256" },
      { name: "validBefore", type: "uint256" },
      { name: "nonce", type: "bytes32" },
      { name: "v", type: "uint8" },
      { name: "r", type: "bytes32" },
      { name: "s", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "authorizationState",
    stateMutability: "view",
    inputs: [
      { name: "authorizer", type: "address" },
      { name: "nonce", type: "bytes32" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "transfer",
    stateMutability: "nonpayable",
    inputs: [
      { name: "to", type: "address" },
      { name: "value", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
] as const;
