// Regenerates committed ABI modules from Foundry artifacts.
// Usage: pnpm abis  (runs `forge build` first; artifacts land in packages/contracts/out)
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const contractsOut = join(here, "..", "..", "contracts", "out");
const abisDir = join(here, "..", "src", "abis");

function loadAbi(file, name) {
  const artifact = JSON.parse(readFileSync(join(contractsOut, file, `${name}.json`), "utf8"));
  return artifact.abi;
}

function emit(fileName, exportName, abi) {
  const body = `// AUTO-GENERATED by \`pnpm abis\` from Foundry artifacts — do not edit.\nexport const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(join(abisDir, fileName), body);
  console.log(`wrote src/abis/${fileName} (${abi.length} entries)`);
}

mkdirSync(abisDir, { recursive: true });

emit("gantryCore.ts", "gantryCoreAbi", loadAbi("GantryCore.sol", "GantryCore"));
emit("fixedRateSwap.ts", "fixedRateSwapAbi", loadAbi("FixedRateSwap.sol", "FixedRateSwap"));
emit("agentPbmWallet.ts", "agentPbmWalletAbi", loadAbi("AgentPBMWallet.sol", "AgentPBMWallet"));
emit(
  "agentPbmWalletFactory.ts",
  "agentPbmWalletFactoryAbi",
  loadAbi("AgentPBMWalletFactory.sol", "AgentPBMWalletFactory"),
);
emit(
  "eip3009Errors.ts",
  "eip3009ErrorsAbi",
  loadAbi("EIP3009.sol", "EIP3009").filter((entry) => entry.type === "error"),
);
